name: MyST Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

env:
  BASE_URL: /${{ github.event.repository.name }}
  GALLERY_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
  BASE_REPO_BRANCH: main    # Wichtig für clone_sync_repos.py

jobs:
  build-and-deploy:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Gallery Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          pip install pyyaml nbformat
          npm install -g mystmd

      - name: Sync notebooks from Lab + external cookbooks
        run: python scripts/clone_sync_repos.py
      
      - name: DEBUG — show images after sync
        run: |
          echo "=== IMAGES FOUND IN img/ ==="
          ls -R img || echo "No img folder"


      - name: Generate gallery markdown files
        run: python scripts/generate_gallery_md.py

      - name: Generate keywords markdown files
        run: python scripts/gallery_keywords.py

      - name: Generate Buttons in index file
        run: python scripts/indexbutton.py

      - name: Copy images into final HTML folder
        run: |
          echo "Copy dynamic images into HTML folder..."
          mkdir -p "${{ github.workspace }}/_build/html/img"
          cp -r "${{ github.workspace }}/img/"* "${{ github.workspace }}/_build/html/img/" || true
      
        
      - name: DEBUG — check img/ in workspace
        run: |
          echo "=== WORKSPACE LOCATION ==="
          pwd
          echo "=== LIST OF FILES ==="
          ls -R .
          echo "=== LIST OF ./img ==="
          ls -R img || echo "img not found"


      - name: Generate myst.yml and TOC
        run: python scripts/build_myst_yml.py

      - name: Build MyST HTML site
        run: myst build --html

      - name: DEBUG — show images in HTML build
        run: |
          echo "=== IMAGES IN _build/html/img ==="
          ls -R _build/html/img || echo "No html img folder"


      - name: DEBUG — show final deploy folder images
        run: |
          echo "=== IMAGES IN full_site/img ==="
          ls -R full_site/img || echo "No images in final site"


      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
